### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by bcomnes** [netlify/netlify-identity-widget#5]
# Architecture Milestones:

- [x] Basic API defined (https://github.com/netlify/netlify-identity/blob/master/README.md)
- [x] Modal app controller (https://github.com/netlify/netlify-identity/blob/master/index.js)
- [x] Modal component (https://github.com/netlify/netlify-identity/blob/master/components/modal.js)
- [x] Dev environment (live-reload, module and UMD APIs) (https://github.com/netlify/netlify-identity/blob/master/package.json#L43-L45)
- [x] UMD build step (https://github.com/netlify/netlify-identity/blob/master/package.json#L48-L53)
- [x] UMD example site (https://netlify-identity.netlify.com)
- [x] Scoped css with [csjs](https://github.com/rtsao/csjs) with bundle extraction so we don't clobber our users css or impose side effects (https://github.com/netlify/netlify-identity/blob/master/components/styles.csjs.js) 
- [ ] Native CSS Vars.  Right now we only support JS ones via csjs.
- [x] Babel.  Had to disable due to difficulties with the UMD build, but will revisit if necessary.
- [x] Querystring formatted Hash handling / routing (necessary for confirm link backs)
- [x] All styling
- [x] Icons 
- [ ] Provider assets
- [x] Message Flash
- [x] Error Flash

# Feature Milestones:

- [x] Modal mounts
- [x] Modal opens and closes
- [x] Can navigate between login and signup forms
- [x] Can Signup
- [x] Can Login
- [ ] Remember me checkbox
- [x] Can confirm signup
- [x] Can request password recovery
- [x] Can recover password
- [x] Can log out
- [ ] Emits all documented events
- [ ] Make it work on Kaldi template

# Possible features

- [ ] iframe architecture (https://github.com/netlify/netlify-identity-widget/issues/17)
- [ ] Login button island markup
- [ ] Display relevant state in UI
